services:

    FrontendPermissionToolkitBundle\Service:
        autoconfigure: true
        autowire: true

    bundle.frontendpermissiontoolkit.service:
        alias: FrontendPermissionToolkitBundle\Service